### ISSUE TITLE
can't run in Apple M1.

### ISSUE THREAD

**Issue by humbleCoder1990** [11ols/11dragfiles#1]
Could you re-compile dragfiles for M1 chip?
Thanks!

**Comment by 11ols** [comment]
Yes, is on my todo list.

**Comment by humbleCoder1990** [comment]
Thanks 11ols. 
Your external is amazing , C74 should include them as "core objects"...
I don't know why they did't make object to drag any files from Max to other external applications.
Your approach is really clever, and I see it's very long codes to support cross platform.
Is it a lot of works to rebuild external for M1?

**Comment by 11ols** [comment]
Thanks. Yes, I think it should be an essential feature for a programming tool.
I hope recompiling is straight forward. I haven't tried yet with any of the Mac externals.

**Comment by humbleCoder1990** [comment]
I tried to make C external, too 
So can we access OS API in C external? 
Do you think you can write [dragfiles] using C++, not C?

**Comment by 11ols** [comment]
Windows API is in C and OSX API is in objective C, so I don't see the reason to switch to C++ in this case.

**Comment by humbleCoder1990** [comment]
When can I see M1 version?

**Comment by 11ols** [comment]
Can you test the download from the webpage so I can close this issue?

**Comment by humbleCoder1990** [comment]
Oh Is it M1 version?!!!

**Comment by humbleCoder1990** [comment]
I see this warning box after opening "help" patcher.

"External cannet bo loaded due to macOS quarantine"
"Max can attept to remove quarantine attributes from 11dragfiles.mxo."
"Proceed?"

Then I clicked "OK", then I can use help file finally.
But the end user ("max for live user") would see this warning window,too?

**Comment by 11ols** [comment]
Yes this warning came with Catalina and has been discussed much in the forums. That's Apple raising security levels more and more until no independent devs can release anything for Mac. But I think If the external is frozen into a m4l device there won't be any warnig. You should try out to be sure. I close this issue as it seems to work with Apple Silicon now.

**Comment by humbleCoder1990** [comment]
Thanks oleson. 
Can I use [11dragfiles] for any commercial Max For Live device?

**Comment by 11ols** [comment]
Yes, use it anywhere!

**Comment by humbleCoder1990** [comment]
Thanks olsen. 
You should know you are saving someone' life!!!!
You did amazing job the cross platform [11dragfiles].
It's something C74 missed really.
Thanks inifnite alot...
