### ISSUE TITLE
Any plan to make kineof [createfiles] ? 

### ISSUE THREAD

**Issue by humbleCoder1990** [11ols/11dragfiles#3]
Sorry posting to ask kind of "new object"

I would like to see [creatfolder] & [createfile] object really. 

To do this, in Max I should use [node.script].
Is there any plan like this?

**Comment by 11ols** [comment]
there's a [createfolder] in Jasch objects http://www.jasch.ch/dl/jasch_objects_0_8_2.zip. And files you can create by saving for example with the text object in Max.

**Comment by 11ols** [comment]
And there is a [shell] object to do any command line operation on Windows and Mac. Search for shell on the forums. Although I don't know if that has been updated to support apple silicon yet
